### PR TITLE
Remove batch processing and other minor updates.

### PR DESCRIPTION
**Pull request by murli-9585**
1. Remove batch processing.
2. Revert un-intended changes in pid.py from PR 13
3. Add yellow light to publishing - Re-add from PR 17; in simplified form.

### CODE REVIEW

**Comment by MikeZhu92** [comment]
Fresh cloned the repo with PR. The error still exists
`IndexError: deque index out of range`

```[waypoint_updater-7] process has died [pid 4687, exit code 1,```

got a warning as well `[WARN] [1523040564.125566]: Distance to TL > LOOKAHEAD_WPS`

**Comment by murli-9585** [comment]
Deque index out of range was introduced with previous PR. This work is different for that work. That bug need to be addressed separately.

**Comment by MikeZhu92** [comment]
@murli-9585 Please test the code before sending out PR. If you think the tl_detector introducing logic conflict. Please include the revert version of the `tl_detector.py` in this PR so that other team members can test it.

**Comment by ablacklama** [comment]
Is this ready for merging?

**Pull request merged**
